version: '3.8'

services:
  email-reader:
    build: .
    container_name: email-reader
    environment:
      - EMAIL_SERVER=imap.gmail.com
      - EMAIL_PORT=993
      - EMAIL_USER=timesync.upload@gmail.com
      - EMAIL_PASSWORD=iqlbpslhqmekvted
    volumes:
      - ./downloads:/app/downloads
